import type { ScoringSystemsBySport } from "../../types.js";

export const scoringSystems: ScoringSystemsBySport = {
  ncaafb: {
    passing_td: { name: "Passing Touchdowns", score: 4, key: "passing.touchdowns" },
    passing_yds: { name: "Passing Yards", score: 0.01, key: "passing.yards" },
    interception: { name: "Interception", score: -1, key: "passing.interceptions" },
    rushing_td: { name: "Rushing Touchdowns", score: 6, key: "rushing.touchdowns" },
    rushing_yds: { name: "Rushing Yards", score: 0.01, key: "rushing.yards" },
    receiving_td: { name: "Receiving Touchdowns", score: 6, key: "receiving.touchdowns" },
    receiving_yds: { name: "Receiving Yards", score: 0.01, key: "receiving.yards" },
    reception: { name: "Reception", score: 1, key: "receiving.receptions" },
    punt_returns: { name: "Punt Return for TD", score: 6, key: "punt_returns.touchdowns" },
    fumble: { name: "Fumble Lost", score: -1, key: "fumbles.fumbles" },
    two_point_conversion_pass: { name: "2 Pt Conversion Pass", score: 2, key: "conversions.pass_successes" },
    two_point_conversion_rush: { name: "2 Pt Conversion Rushing", score: 2, key: "conversions.rush_successes" },
    two_point_conversion_receiving: { name: "2 Pt Conversion Receiving", score: 2, key: "conversions.receive_successes" },
    solo_tackle: { name: "Solo Tackle", score: 1.5, key: "defense.tackles" },
    assisted_tackle: { name: "Assisted Tackle", score: 0.75, key: "defense.assists" },
    tackle_for_loss: { name: "Tackle for loss", score: 2, key: "defense.tloss" },
    sack: { name: "Sack", score: 4, key: "defense.sacks" },
    interceptions: { name: "Defense Interception", score: 4, key: "defense.interceptions" },
    forced_fumble: { name: "Forced fumble", score: 4, key: "defense.forced_fumbles" },
    fumble_recovery: { name: "Defense Fumble Recovery", score: 4, key: "defense.fumble_recoveries" },
    defensive_td: { name: "Defensive TD", score: 6, key: "rushing.touchdowns" },
    safety: { name: "Safety", score: 2, key: "defense.safeties" },
    pass_defensed: { name: "Pass defensed", score: 1.5, key: "defense.passes_defended" },
  },
  nfl: {
    passing_td: { name: "Passing Touchdowns", score: 4, key: "passing.touchdowns" },
    passing_yds: { name: "Passing Yards", score: 0.01, key: "passing.yards" },
    interception: { name: "Interception", score: -1, key: "passing.interceptions" },
    rushing_td: { name: "Rushing Touchdowns", score: 6, key: "rushing.touchdowns" },
    rushing_yds: { name: "Rushing Yards", score: 0.01, key: "rushing.yards" },
    receiving_td: { name: "Receiving Touchdowns", score: 6, key: "receiving.touchdowns" },
    receiving_yds: { name: "Receiving Yards", score: 0.01, key: "receiving.yards" },
    reception: { name: "Reception", score: 1, key: "receiving.receptions" },
    punt_returns: { name: "Punt Return for TD", score: 6, key: "punt_returns.touchdowns" },
    fumble: { name: "Fumble Lost", score: -1, key: "fumbles.fumbles" },
    two_point_conversion_pass: { name: "2 Pt Conversion Pass", score: 2, key: "conversions.pass_successes" },
    two_point_conversion_rush: { name: "2 Pt Conversion Rushing", score: 2, key: "conversions.rush_successes" },
    two_point_conversion_receiving: { name: "2 Pt Conversion Receiving", score: 2, key: "conversions.receive_successes" },
    solo_tackle: { name: "Solo Tackle", score: 1.5, key: "defense.tackles" },
    assisted_tackle: { name: "Assisted Tackle", score: 0.75, key: "defense.assists" },
    tackle_for_loss: { name: "Tackle for loss", score: 2, key: "defense.tloss" },
    sack: { name: "Sack", score: 4, key: "defense.sacks" },
    interceptions: { name: "Defense Interception", score: 4, key: "defense.interceptions" },
    forced_fumble: { name: "Forced fumble", score: 4, key: "defense.forced_fumbles" },
    fumble_recovery: { name: "Defense Fumble Recovery", score: 4, key: "defense.fumble_recoveries" },
    defensive_td: { name: "Defensive TD", score: 6, key: "rushing.touchdowns" },
    safety: { name: "Safety", score: 2, key: "defense.safeties" },
    pass_defensed: { name: "Pass defensed", score: 1.5, key: "defense.passes_defended" },
  },
  nhl: {
    goals: { name: "Goals", score: 8.5, key: "total.goals" },
    assist: { name: "Assist", score: 5, key: "total.assists" },
    shot_on_goal: { name: "Shot on Goal", score: 1.5, key: "total.shots" },
    blocked_shot: { name: "Blocked Shot", score: 1.4, key: "total.blocked_shots" },
    shoot_out_goal: { name: "Shootout Goal", score: 1.5, key: "shootout.goals" },
    goalies_win: { name: "Goalies Win", score: 6, key: "total.credit", value: "win" },
    goalies_save: { name: "Goalies Save", score: 0.7, key: "total.saves" },
    goalies_overtime_loss: { name: "Goalies Overtime Loss", score: 2, key: "total.credit", value: "overtime_loss" },
    goalies_goals_against: { name: "Goalies Goals Against", score: -3.5, key: "total.goals_against" },
  },
  nba: {
    points: { name: "Point", score: 1, key: "points" },
    three_points_made: { name: "Made 3pt Shot", score: 0.5, key: "three_points_made" },
    rebounds: { name: "Rebound", score: 1.25, key: "rebounds" },
    assists: { name: "Assist", score: 1.5, key: "assists" },
    steals: { name: "Steals", score: 2, key: "steals" },
    blocks: { name: "Block", score: 2, key: "blocks" },
    turnovers: { name: "Turnover", score: -0.5, key: "turnovers" },
  },
  mlb: {
    single: { name: "Single", score: 3, key: "hitting.overall.onbase.s" },
    double: { name: "Double", score: 5, key: "hitting.overall.onbase.d" },
    triple: { name: "Triple", score: 8, key: "hitting.overall.onbase.t" },
    home_runs: { name: "Home Run", score: 10, key: "hitting.overall.onbase.hr" },
    rbi: { name: "Run Batted In", score: 2, key: "hitting.overall.rbi" },
    run: { name: "Run", score: 2, key: "hitting.overall.runs.total" },
    base_on_balls: { name: "Base on Balls", score: 2, key: "hitting.overall.onbase.bb" },
    hit_by_pitch: { name: "Hit By Pitch", score: 2, key: "hitting.overall.onbase.hbp" },
    stolen_base: { name: "Stolen Base", score: 5, key: "hitting.overall.steal.stolen" },
    inning_pitch: { name: "Inning Pitched", score: 2.25, key: "pitching.overall.ip_2" },
    strikeout: { name: "Strikeout", score: 2, key: "pitching.overall.outs.ktotal" },
    win: { name: "Win", score: 4, key: "pitching.overall.games.win" },
    era: { name: "Earned Run Allowed", score: -2, key: "pitching.overall.runs.earned" },
    hit_agianst: { name: "Hit Against", score: -0.6, key: "pitching.overall.onbase.h" },
    base_on_balls_agianst: { name: "Base on Balls Against", score: -0.6, key: "pitching.overall.onbase.bb" },
    hit_batsman: { name: "Hit Batsman", score: -0.6, key: "pitching.overall.onbase.hbp" },
    complete_game: { name: "Complete Game", score: 2.5, key: "pitching.overall.games.complete" },
    shut_out: { name: "Shutout", score: 2.5, key: "pitching.overall.games.shutout" },
  },
  soccer: {
    goal: { name: "Goal", score: 10, key: "goals.total" },
    assist: { name: "Assist", score: 6, key: "goals.assists" },
    shot_on_target: { name: "Shot on Target", score: 2, key: "shots.on" },
    key_pass: { name: "Key Pass", score: 3, key: "passes.key" },
    tackle: { name: "Tackle", score: 2, key: "tackles.total" },
    interception: { name: "Interception", score: 2, key: "tackles.interceptions" },
    save: { name: "Save", score: 3, key: "goals.saves" },
    clean_sheet: { name: "Clean Sheet", score: 5, key: "goals.conceded", value: "0" },
    yellow_card: { name: "Yellow Card", score: -1, key: "cards.yellow" },
    red_card: { name: "Red Card", score: -3, key: "cards.red" },
    goals_conceded: { name: "Goals Conceded", score: -2, key: "goals.conceded" },
  },
};
