import type { ScoringSystemsBySport } from "../../types.js";

export const scoringSystemsTeam: ScoringSystemsBySport = {
  ncaafb: {
    passing_td: { name: "Passing Touchdowns", score: 4, key: "passing.touchdowns" },
    passing_yds: { name: "Passing Yards", score: 0.01, key: "passing.yards" },
    interception: { name: "Interception", score: -1, key: "passing.interceptions" },
    rushing_td: { name: "Rushing Touchdowns", score: 6, key: "rushing.touchdowns" },
    rushing_yds: { name: "Rushing Yards", score: 0.01, key: "rushing.yards" },
    receiving_td: { name: "Receiving Touchdowns", score: 6, key: "receiving.touchdowns" },
    receiving_yds: { name: "Receiving Yards", score: 0.01, key: "receiving.yards" },
    reception: { name: "Reception", score: 1, key: "receiving.receptions" },
    punt_returns: { name: "Punt Return for TD", score: 6, key: "punt_returns.touchdowns" },
    fumble: { name: "Fumble Lost", score: -1, key: "fumbles.fumbles" },
    two_point_conversion_pass: { name: "2 Pt Conversion Pass", score: 2, key: "conversions.pass_successes" },
    two_point_conversion_rush: { name: "2 Pt Conversion Rushing", score: 2, key: "conversions.rush_successes" },
    two_point_conversion_receiving: { name: "2 Pt Conversion Receiving", score: 2, key: "conversions.receive_successes" },
  },
  nfl: {
    passing_td: { name: "Passing Touchdowns", score: 4, key: "passing.touchdowns" },
    passing_yds: { name: "Passing Yards", score: 0.01, key: "passing.yards" },
    interception: { name: "Interception", score: -1, key: "passing.interceptions" },
    rushing_td: { name: "Rushing Touchdowns", score: 6, key: "rushing.touchdowns" },
    rushing_yds: { name: "Rushing Yards", score: 0.01, key: "rushing.yards" },
    receiving_td: { name: "Receiving Touchdowns", score: 6, key: "receiving.touchdowns" },
    receiving_yds: { name: "Receiving Yards", score: 0.01, key: "receiving.yards" },
    reception: { name: "Reception", score: 1, key: "receiving.receptions" },
    punt_returns: { name: "Punt Return for TD", score: 6, key: "punt_returns.touchdowns" },
    fumble: { name: "Fumble Lost", score: -1, key: "fumbles.fumbles" },
    two_point_conversion_pass: { name: "2 Pt Conversion Pass", score: 2, key: "conversions.pass_successes" },
    two_point_conversion_rush: { name: "2 Pt Conversion Rushing", score: 2, key: "conversions.rush_successes" },
    two_point_conversion_receiving: { name: "2 Pt Conversion Receiving", score: 2, key: "conversions.receive_successes" },
  },
  nhl: {
    goals: { name: "Goals", score: 8.5, key: "total.goals" },
    shot_on_goal: { name: "Shot on Goal", score: 1.5, key: "total.shots" },
    blocked_shot: { name: "Blocked Shot", score: 1.4, key: "total.blocked_shots" },
    shoot_out_goal: { name: "Shootout Goal", score: 1.5, key: "shootout.goals" },
  },
  nba: {
    points: { name: "Point", score: 1, key: "points" },
    three_points_made: { name: "Made 3pt Shot", score: 0.5, key: "three_points_made" },
    rebounds: { name: "Rebound", score: 1.25, key: "rebounds" },
    assists: { name: "Assist", score: 1.5, key: "assists" },
    steals: { name: "Steals", score: 2, key: "steals" },
    blocks: { name: "Block", score: 2, key: "blocks" },
    turnovers: { name: "Turnover", score: -0.5, key: "turnovers" },
  },
  mlb: {
    single: { name: "Single", score: 3, key: "hitting.overall.onbase.s" },
    double: { name: "Double", score: 5, key: "hitting.overall.onbase.d" },
    triple: { name: "Triple", score: 8, key: "hitting.overall.onbase.t" },
    home_runs: { name: "Home Run", score: 10, key: "hitting.overall.onbase.hr" },
    rbi: { name: "Run Batted In", score: 2, key: "hitting.overall.rbi" },
    run: { name: "Run", score: 2, key: "hitting.overall.runs.total" },
    base_on_balls: { name: "Base on Balls", score: 2, key: "hitting.overall.onbase.bb" },
    stolen_base: { name: "Stolen Base", score: 5, key: "hitting.overall.steal.stolen" },
  },
};
